### ISSUE TITLE
Switching the order of the challenges

### ISSUE THREAD

**Issue by EarLyMe** [learn-co-students/other-hash-methods-code-along-v-000#148]
I feel like the code-along under "Challenge 3: Return the values" that deals with flattening values in a hash should come before "Challenge 2: Return the min", since challenge 2 actually requires you to use the methods outlined in challenge 3. As I read through it, it seemed like in challenge 2 you were expected to know what the values and flatten methods were but you didn't actually learn about them until you got to challenge 3. Felt really awkward.

**Comment by ga-be** [comment]
Seems to have been fixed: https://github.com/learn-co-students/other-hash-methods-code-along-v-000/commit/ae59303bb518d0d6250affa3078e8fded995e2c3

cc: @MsUzoAgu
