### ISSUE TITLE
bin files fail to execute

### ISSUE THREAD

**Issue by thegands** [learn-co-students/other-hash-methods-code-along-v-000#95]
when executing the bin files, they do not pass the required argument when calling their respective methods and therefore fail to execute. the groceries hash should be set up in each bin file before calling the method and the method should be called with the groceries argument.

**Comment by pletcher** [comment]
Fixed -- something majorly wonky happened with the git history https://github.com/learn-co-students/other-hash-methods-code-along-v-000/commit/9137741a08b1d2e2ededc061aa46f25111587b93
